version: '3.8'

services:
  #Banco de Dados
  db:
    image: mysql:8.0
    container_name: deliverit-db
    environment:
      MYSQL_DATABASE: deliverit_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data_v2:/var/lib/mysql
    networks:
      - deliverit-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10

  #Backend Java
  backend:
    build: .
    container_name: deliverit-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/deliverit_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - deliverit-network

  #Frontend Angular
  frontend:
    build: ./frontend
    container_name: deliverit-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - deliverit-network

volumes:
  db_data_v2:

networks:
  deliverit-network:
    driver: bridge